name: jit-install-smoke

on:
  workflow_dispatch:
  workflow_call:

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn oclif manifest
      - uses: actions/upload-artifact@v3
        with:
          name: manifest
          path: oclif.manifest.json

  get-jit-plugins:
    runs-on: ubuntu-latest
    outputs:
      jit: ${{ steps.plugins.outputs.jit }}
    steps:
      - uses: actions/checkout@v4

      - name: Get JIT plugins
        id: plugins
        # This was a pain to get working, be weary of changing it...
        # For the dynamic matrix to work, you have to have a VERY specific format:
        # Output must be multiline (no jq -c), quotes matter, cannot use toJSON on output, etc...
        # The dynamic matrix needs to use fromJSON when reading the needs output
        # Multiline format: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        run: |
          {
            echo 'jit<<EOF'
            jq '.oclif.jitPlugins | keys' package.json
            echo EOF
          } >> "$GITHUB_OUTPUT"

  jit-install:
    needs: [manifest, get-jit-plugins]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jitPlugins: ${{ fromJSON(needs.get-jit-plugins.outputs.jit) }}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}

      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
        with:
          ignore-scripts: true

      - run: yarn build

      - uses: actions/download-artifact@v3
        with:
          name: manifest

      - name: Install JIT plugin
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          command: yarn sf-release cli:install:jit:test --jit-plugin $MATRIX_JIT_PLUGINS
        env:
          MATRIX_JIT_PLUGINS: ${{ matrix.jitPlugins }}
          SF_DISABLE_TELEMETRY: true
