name: ut and tarballs

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ut-tarballs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main

  ut:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
    secrets: inherit

  tarballs:
    uses: salesforcecli/github-workflows/.github/workflows/tarballs.yml@main
    with:
      nodeVersion: ${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}
    secrets: inherit

  # DONE
  jit-install-smoke:
    uses: ./.github/workflows/jit-install-smoke.yml
    secrets: inherit

  artifacts:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}
          cache: yarn
      - run: yarn install
      - run: yarn test:deprecation-policy
